openapi: 3.0.3
info:
  title: Clock Service Demo
  description: |-
    Put describing text here

  contact:
    email: lukas.tietenberg@outlook.de

  license:
    name: MIT
    url: https://github.com/sourcefranke/clock-service-demo-api?tab=MIT-1-ov-file

  version: 1.0.11

servers:
  - url: http://localhost:8080

tags:
  - name: time
    description: Take your time ;P

paths:
  /time:
    get:
      tags:
        - time
      summary: Finds Pets by tags
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: getTime
      parameters:
        - name: format
          in: query
          description: Specify format for date and/or time
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '400':
          description: Invalid tag value
